#install all dependencies for correct work of wordpress
- name: update & upgrade
  ansible.builtin.apt:
    upgrade: yes
    update_cache: 'true'
  become: true

- name: gcsfuse install
  ansible.builtin.shell: |
    export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
    echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    sudo apt update
    sudo apt install gcsfuse -y
    sudo echo user_allow_other >> /etc/fuse.conf
  become: true

- name: installing all dependencies
  apt:
    name: '{{item}}'
    state: installed
    with_items:
      - php
      - php-curl
      - php-common
      - php-mbstring
      - php-gd
      - php-intl
      - php-xml
      - php-mysql
      - php-fpm
      - php-zip
      - apache2
      - unzip
    become: true
    when: "'web-servers' in group_names"

#Enable apache2 service for normally work

- name: enable apache
  service:
    name: apache2
    enabled: yes
  become: true
  when: "'web-servers' in group_names"

#Change config for apache2 default-site

- name: upload config for apache default site
  ansible.builtin.copy:
    src: /ansible/roles/wordpress/files/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: pfaka
    mode: '0644'
  become: true
  when: "'web-servers' in group_names"

#Change config for upload dir

- name: upload config for apache dir.conf
  ansible.builtin.copy:
    src: /ansible/roles/wp-deploy/files/dir.conf
    dest: /etc/apache2/mods-enabled/dir.conf
    owner: pfaka
    mode: '0644'
  become: true
  when: "'web-servers' in group_names"

# Enabling rewrite mode for apache2

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present
  become: true
  notify:
    -restart apache

- name: download wordpress
  ansible.builtin.shell: |
    (cd /mnt && sudo -u pfaka wget https://wordpress.org/latest.zip)
    (cd /mnt && sudo -u pfaka unzip latest.zip)
    (cd /mnt/wordpress/wp-content/plugins && wget https://downloads.wordpress.org/plugin/ssl-insecure-content-fixer.2.7.2.zip)
    (cd /mnt/wordpress/wp-content/plugins && unzip ssl-insecure-content-fixer.2.7.2.zip)
    (cd /mnt/wordpress/wp-content/plugins && rm -rf ssl-insecure-content-fixer.2.7.2.zip)
    sudo chmod 777 /mnt/wordpress -R
  become: true

- name: upload wordpress to bucket
  ansible.builtin.shell: |
    (cd /mnt && sudo chown www-data:www-data wordpress -R)
    (cd /mnt && sudo -u pfaka gsutil -m cp -r wordpress/* gs://{{bucket}})
    (cd /mnt && sudo -u pfaka rm latest.zip)
    (cd /mnt && sudo -u pfaka rm -rf wordpress)
  become: true

- name:
  ansible.builtin.shell: |
    (gcsfuse -o nonempty -o allow_other --dir-mode 755 {{bucket}} /mnt)
  become: true

- name: Create symbolic link
  file:
    src: "/mnt"
    dest: "/var/www/"
    state: link
