#install all dependencies for correct work of wordpress
- name: update & upgrade
  ansible.builtin.apt:
    upgrade: yes
    update_cache: 'true'
  become: True

- name: gcsfuse install
  ansible.builtin.shell: |
    export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
    echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    sudo apt update
    sudo apt install gcsfuse -y
    sudo echo user_allow_other >> /etc/fuse.conf
  become: true

- name: installing all dependencies
  ansible.builtin.apt:
      pkg:
      - php
      - php-curl
      - php-common
      - php-mbstring
      - php-gd
      - php-intl
      - php-xml
      - php-mysql
      - php-fpm
      - php-zip
      - apache2
      - unzip
  become: true

#Enable apache2 service for normally work

- name: enable apache
  service:
    name: apache2
    enabled: yes
  become: true

#Change config for apache2 default-site

- name: upload config for apache default site
  ansible.builtin.copy:
    src: ../files/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: pfaka
    mode: '0644'
  become: true

#Change config for upload dir

- name: upload config for apache dir.conf
  ansible.builtin.copy:
    src: ../files/dir.conf
    dest: /etc/apache2/mods-enabled/dir.conf
    owner: pfaka
    mode: '0644'
  become: true

# Enabling rewrite mode for apache2

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present
  become: true

- name: download wordpress
  ansible.builtin.shell: |
    wget https://wordpress.org/latest.zip
    unzip latest.zip
    rm -f latest.zip
    sudo chmod 777 ./wordpress -R
  become: true

- name: download plugin
  ansible.builtin.shell: |
    wget https://downloads.wordpress.org/plugin/ssl-insecure-content-fixer.2.7.2.zip 
    unzip ssl-insecure-content-fixer.2.7.2.zip
    rm -rf ssl-insecure-content-fixer.2.7.2.zip
  args:
    chdir: wordpress/wp-content/plugins
  become: true

- name: upload wordpress to bucket
  ansible.builtin.shell: |
    sudo chown www-data:www-data wordpress -R
    sudo gsutil -m cp -r wordpress/* gs://{{bucket}}
    sudo rm -rf wordpress
  become: true

