---
- name: update & upgrade
  ansible.builtin.apt:
    update_cache: 'true'
  become: true
  
- name: gcsfuse install
  ansible.builtin.shell: |
    export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
    echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    sudo apt update
    sudo apt install gcsfuse -y
    sudo echo user_allow_other >> /etc/fuse.conf
  become: true

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - apache2
    - php 
    - libapache2-mod-php
    - php-mysql
    - unzip
    - php-curl
    - php-common
    - php-mbstring
    - php-gd
    - php-intl
    - php-xml
    - php-fpm
    - php-zip
    - ghostscript
    - php-bcmath
    - php-imagick
    - php-json
  become: true  

- name: download wordpress
  ansible.builtin.shell: |
    wget https://wordpress.org/latest.zip
    unzip latest.zip
    rm -f latest.zip
    sudo chmod 777 ./wordpress -R
  become: true

- name: download plagin
  ansible.builtin.shell: |
    wget https://downloads.wordpress.org/plugin/ssl-insecure-content-fixer.2.7.2.zip 
    unzip ssl-insecure-content-fixer.2.7.2.zip
    rm -rf ssl-insecure-content-fixer.2.7.2.zip
  args:
    chdir: wordpress/wp-content/plugins
  become: true

- name: wp-config.php template a file 
  ansible.builtin.template:
    src: ../templates/wp-config
    dest: ./wordpress/wp-config.php
    owner: pfaka
    mode: '0755'
  become: true

- name: htaccess file
  ansible.builtin.copy:
    src: ../files/htaccess
    dest: ./wordpress/.htaccess
    mode: "0755"
    owner: pfaka
  become: true

- name: upload wordpress to bucket
  ansible.builtin.shell: |
    sudo chown www-data:www-data wordpress -R
    sudo gsutil -m cp -r wordpress/* gs://{{bucket}}
    sudo rm -rf wordpress
  become: true

- name: ops-agent install
  ansible.builtin.shell: |
   curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
   sudo bash add-google-cloud-ops-agent-repo.sh --also-install
  become: true

- name: default.conf file
  ansible.builtin.copy:
    src: ../files/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
    mode: "0755"
    owner: pfaka
  become: true
  notify:
  - restart apache